import turtle

turtle.penup()
turtle.goto(-150,80)
turtle.pendown()
turtle.color("light blue")
turtle.pensize(10)
turtle.circle(40)
turtle.penup()
turtle.goto(-100,40)
turtle.pendown()
turtle.color("yellow")
turtle.circle(40)
turtle.penup()
turtle.goto(-50,80)
turtle.pendown()
turtle.color("black")
turtle.circle(40)
turtle.penup()
turtle.goto(0,40)
turtle.pendown()
turtle.color("green")
turtle.circle(40)
turtle.penup()
turtle.goto(50,80)
turtle.pendown()
turtle.color("red")
turtle.circle(40)

input("Enter value to close program")