import turtle

turtle.speed(10)
turtle.bgcolor('grey')

turtle.penup()
turtle.goto(0, -150)
turtle.pendown()
turtle.circle(80)
turtle.penup()
turtle.goto(0, 0)
turtle.pendown()
turtle.circle(70)

turtle.penup()
turtle.goto(-30, 50)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(20)
turtle.end_fill()

turtle.fillcolor("black")
turtle.begin_fill()
turtle.penup()
turtle.goto(30, 50)
turtle.pendown()
turtle.circle(20)
turtle.end_fill()

turtle.penup()
turtle.goto(30, 60)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()

turtle.penup()
turtle.goto(-30, 60)
turtle.pendown()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.circle(7)
turtle.end_fill()

turtle.penup()
turtle.goto(0, 35)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(13)
turtle.end_fill()

turtle.penup()
turtle.goto(-65, 95)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()


turtle.penup()
turtle.goto(65, 95)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(25)
turtle.end_fill()


turtle.penup()
turtle.goto(-100, 20)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.right(35)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.end_fill()

turtle.penup()
turtle.goto(100, 20)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.left(-10)
turtle.forward(-60)
turtle.left(90)
turtle.forward(-30)
turtle.left(90)
turtle.forward(-60)
turtle.left(90)
turtle.forward(-30)
turtle.end_fill()

turtle.penup()
turtle.goto(-65, -190)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.left(120)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.right(90)
turtle.forward(60)
turtle.right(90)
turtle.forward(30)
turtle.end_fill()

turtle.penup()
turtle.goto(65, -190)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.left(120)
turtle.forward(-60)
turtle.left(90)
turtle.forward(-30)
turtle.left(90)
turtle.forward(-60)
turtle.left(90)
turtle.forward(-30)
turtle.end_fill()

input("Enter value to close program")