import turtle

turtle.bgcolor("#638ED4")
turtle.penup()
turtle.fillcolor("white")
turtle.begin_fill()
turtle.goto(0, -170)
turtle.pendown()
turtle.pensize(4)
turtle.circle(80)
turtle.penup()
turtle.goto(0, -10)
turtle.pendown()
turtle.circle(55)
turtle.penup()
turtle.goto(0, 95)
turtle.pendown()
turtle.circle(45)
turtle.end_fill()
turtle.penup()
turtle.goto(-10, 140)
turtle.pendown()
turtle.fillcolor("black")
turtle.begin_fill()
turtle.circle(5)
turtle.penup()
turtle.goto(10, 140)
turtle.pendown()
turtle.circle(5)
turtle.end_fill()
turtle.penup()
turtle.goto(-10, 130)
turtle.pendown()
turtle.forward(25)
turtle.penup()
turtle.goto(40, 40)
turtle.pendown()
turtle.pensize(10)
turtle.color("brown")
turtle.forward(60)
turtle.penup()
turtle.goto(-40, 40)
turtle.pendown()
turtle.forward(-60)

input("Enter value to close program")